data:
  raw: data/raw/flowers
  train_size: 300
  val_size: 30

clip:
  max_length: 77

vae:
  image_size: [128, 128]

DDPMScheduler:
  T: 300

unet:
  image_size: [16, 16]
  in_channels: 4
  out_channels: 4
  down_block_types: ["CrossAttnDownBlock2D", "DownBlock2D", "CrossAttnDownBlock2D"]
  up_block_types: ["CrossAttnUpBlock2D", "UpBlock2D", "CrossAttnUpBlock2D"]
  mid_block_type: "UNetMidBlock2DCrossAttn"
  block_out_channels: [64, 128, 256]
  layers_per_block: 2
  norm_num_groups: 32
  cross_attention_dim: 512
  attention_head_dim: 12
  dropout: 0.1
  time_embedding_type: "positional"
  act_fn: "silu"

training:
  batch_size: 4
  vae_learning_rate: 5e-5
  unet_learning_rate: 1e-3
  weight_decay: 1e-4
  num_epochs: 10

mlflow_pretraining:
  server_uri: sqlite:///mlflow.db
  experiment_name: Training
  run_name: 1st
  registered_model_name: Diffusion

log_trained_model:
  vae_dir: saved_models/vae.pth
  diffuser_dir: saved_models/diffuser.pth