data:
  raw: data/raw/flowers
  train_size: 3000
  val_size: 500

clip:
  max_length: 77

vae:
  image_size: 128,128

DDPMScheduler:
  T: 1000

unet:
  image_size: 16,16
  in_channels: 4
  out_channels: 4
  down_block_types: CrossAttnDownBlock2D
  up_block_types: CrossAttnUpBlock2D
  mid_block_type: UNetMidBlock2DCrossAttn
  block_out_channels: '1024'
  layers_per_block: 2
  norm_num_groups: 16
  cross_attention_dim: 768
  attention_head_dim: 64
  dropout: 0.05
  time_embedding_type: positional
  act_fn: silu

training:
  batch_size: 16
  vae_learning_rate: 1e-4
  unet_learning_rate: 2e-4
  weight_decay: 1e-2
  num_epochs: 10

mlflow:
  server_uri: https://dagshub.com/aniketpoojari/Text-To-Image-Diffusion.mlflow
  # server_uri: http://127.0.0.1:5000
  experiment_name: Training Diffusion 5
  run_name: 1st
  registered_model_name: Diffusion
  tracking_username: aniketpoojari
  tracking_password: 38fa619a54d7cdde5e6dcaa55a01a1c14f329bc2
  s3_mlruns_bucket: text-to-image-aniket-mlflow

log_trained_model:
  vae_dir: saved_models/vae.pth
  diffuser_dir: saved_models/diffuser.pth

pytorch_estimator:
    entry_point: training_sagemaker_deepspeed.py
    source_dir: src/code
    framework_version: '2.6.0'
    py_version: py312
    role: arn:aws:iam::975050169307:role/text-to-image-role
    instance_count: 2
    instance_type: ml.g4dn.xlarge
    max_wait: 7200
    max_run: 7200
    use_spot_instances: True
    s3_train_data: s3://text-to-image-aniket